### ISSUE TITLE
能否加一个podspec 文件，现在管理第三方都在用cocoapods

### ISSUE THREAD

**Issue by csc-EricWu** [lifution/AudioConverter#2]

**Comment by csc-EricWu** [comment]
之前用到过amr 转换wav 的框架，今天看你这边也有个，能否写个podspec文件，方便集成

**Comment by lifution** [comment]
现已支持 CocoaPods 安装，在你的 Podfile 文件中 加入 `pod 'FSAudioConverter'` 然后执行 `pod update` 即可。😀
需要注意的是，如果使用 CocoaPods 安装则不可使用 `use_frameworks!`，必须以静态库的方式引入，否则在使用的时候会编译不通过。

**Comment by csc-EricWu** [comment]
感谢，不能使用use_frameworks! 有什么原因吗？之前库都用了这个参数。

**Comment by lifution** [comment]
貌似是 C 文件解析的问题，暂时还不清楚，网上找了一些资料，好像是可以解决的，等过段时间空闲点后再解决这个问题，到时候跟你说一声。

**Comment by csc-EricWu** [comment]
好的，感谢
