### ISSUE TITLE
不支持bitcode请在podspec里指定相关设置，否则请重新编译支持bitcode

### ISSUE THREAD

**Issue by smithereensarr** [lifution/AudioConverter#3]
支持bitcode的静态库参考：https://github.com/wangweiarr/AMR-for-iOS7

**Comment by lifution** [comment]
已在 `podspec` 文件中添加不支持 Bitcode 的配置。由于该代码库是依赖于第三方的 framework，本人没法重新编译令其支持 Bitcode，给你带来的不便还望见谅。
